### ISSUE TITLE
Implement TCP transport

### ISSUE THREAD

**Issue by plutov** [roistat/go-clickhouse#1]
ClickHouse supports tcp transport by default address localhost:9000

**Comment by flrnull** [comment]
We will investigate TCP transport implementation soon.

**Comment by plutov** [comment]
I will provide a PR soon.

On Wed, Jul 6, 2016 at 5:15 PM, Evgeniy Udodov <notifications@github.com>
wrote:

> We will investigate TCP transport implementation soon.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/roistat/go-clickhouse/issues/1#issuecomment-230733259>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABEp-2M8oLIVagblGHbnsiYnAcNVFHJ8ks5qS4AsgaJpZM4JFyBm>
> .
>



-- 
Skype: alexander_plutov
Phone: +37529 6914945
Blog: plutov.by

**Comment by flrnull** [comment]
Ok, it's great

**Comment by plutov** [comment]
alexey-milovidov commented 5 hours ago
TCP transport is more specific, we don't want to expose details.

Despite we have full compatibility of protocol of different versions of client and server, we want to keep the ability to "break" it for very old clients. And that protocol is not too clean to make a specification.
