### ISSUE TITLE
Add username & password for queries

### ISSUE THREAD

**Issue by SlavaBobik** [roistat/go-clickhouse#21]
Correct me pls if I'm wrong, but now as I can see, there are no ways to set username & password for clickhouse queries?

If this needs, I can create a PR.

**Comment by m1nor** [comment]
Yep, it will be great if you create a PR.

**Comment by a5i** [comment]
I use a connection URL with user name and password like `http://user:password@localhost:8123`

**Comment by SlavaBobik** [comment]
Oh, my bad, @a5i thanks! I think, I could close this issue.
